version = 1

[[annotations]]
path = [
    "keys.txt",
    "sc_to_keep.txt",
    "sc_to_remove.txt"
]

SPDX-FileCopyrightText = [
    "2021,2022,2024,2025 Matija Nalis <mnalis-git@voyager.hr>",
    "2021 smootheFiets <68379371+smootheFiets@users.noreply.github.com>",
    "2022 Tobias Zwick <newton@westnordost.de>",
    "2024 waterced <waterced1@gmail.com>",
    "2024,2025 Mateusz Konieczny <matkoniecz@gmail.com>"
]

SPDX-License-Identifier = "CC0-1.0"
