version = 1

[[annotations]]
path = [
    "keys.txt",
    "sc_to_keep.txt",
    "sc_to_remove.txt"
]

# FIXME: see `TODO.md` and `COPYING` for missing authors
SPDX-FileCopyrightText = [
    "2021,2022,2024,2025 Matija Nalis <mnalis-git@voyager.hr>",
    "2022 Tobias Zwick <newton@westnordost.de>",
    "2024,2025 Mateusz Konieczny <matkoniecz@gmail.com>"
]

SPDX-License-Identifier = "CC0-1.0"
